from typing import TypedDict, List, Dict, Any, Optional
from datetime import datetime

class AgenticOpsState(TypedDict):
    """
    The canonical state contract for the entire AgenticOps-ESG system.

    This object flows through the 7-agent pipeline (Telemetry → RightSizing → 
    Refresh → Compliance → Optimize → Execute → Report). Each agent mutates 
    a specific slice of this state, while the 'audit_trail' logs every decision 
    for regulatory compliance (Bursa/MCMC).
    """
    
    # --- Session & Intent ---
    session_id: str
    """Unique UUID for the current workflow execution."""
    
    user_goal: str
    """High-level human objective (e.g., 'Reduce carbon footprint over 72h')."""
    
    # --- Raw Data (Telemetry Agent) ---
    raw_telemetry: Dict[str, Any]
    """
    Contains live metrics from Prometheus/DCIM, plus grid carbon intensity.
    Structure: {
        "metrics": [{"instance": "...", "cpu_util_pct": 45, "power_draw_watts": 300, ...}],
        "grid_carbon_intensity": 0.58  # kg CO2e per kWh (TNB API)
    }
    """
    
    # --- Analytical Models (Digital Twin) ---
    digital_twin: Dict[str, Any]
    """
    Simulated representations of workloads and hardware degradation.
    Contains pre-processed lists for:
        - "overprovisioned_vms": VMs suitable for right-sizing.
        - "aging_hardware": Servers approaching their refresh crossover point.
        - "current_pue": Current Power Usage Effectiveness.
        - "recycled_kg": E-waste recycled this quarter.
    """
    
    # --- Decision Pipeline ---
    proposed_actions: List[Dict]
    """
    Actions generated by RightSizing and Refresh agents.
    Each dict contains: action (resize/refresh), vm_id/host_id, carbon_saving_kg,
    risk_score, and performance_delta.
    """
    
    compliance_violations: List[str]
    """Human-readable flags raised by the Compliance Agent (e.g., MCMC data residency)."""
    
    approved_execution_plan: Dict
    """The final GitOps/ERP payloads after human approval, structured by action type."""
    
    # --- Observability & Reporting ---
    audit_trail: List[str]
    """
    Immutable, timestamped log of every agent's decision.
    This satisfies Bursa Malaysia's algorithmic transparency requirements.
    """
    
    esg_report_packet: Dict
    """
    Final regulatory output mapped to Bursa, MCMC, GRI 305, and SASB TC-HW/TC-TL.
    Ready for XBRL/PDF generation.
    """